# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Running build script..."
    - python Radiographic_identifier\run.py > build_output.txt
    - echo "Build complete."
  artifacts:
    paths:
      - build_output.txt

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - python unit_tests.py > test_results.txt
    - echo "Unit tests completed."
  artifacts:
    paths:
      - test_results.txt

lint-test-job:
  stage: test
  script:
    - echo "Running lint checks..."
    - python lint_script.py > lint_results.txt
    - echo "Linting completed."
  artifacts:
    paths:
      - lint_results.txt

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - python deploy_script.py > deployment_log.txt
    - echo "Deployment complete. Outputs from previous stages available:"
    - cat build_output.txt
    - cat test_results.txt
    - cat lint_results.txt
  artifacts:
    paths:
      - deployment_log.txt
      - build_output.txt
      - test_results.txt
      - lint_results.txt