
Samples:
  - name: XCT-1
  - name: XCT-2
  - name: XCT-3
  - name: XCT-4
  - name: XCT-5
  - name: XCT-6
  - name: XCT-7
  - name: XCT-8
  - name: XCT-9
  - name: XCT-10
  - name: XCT-11
  - name: XCT-12
  - name: XCT-13
  - name: XCT-14
  - name: XCT-15
  - name: XCT-16
  - name: XCT-17
  - name: XCT-18
  - name: XCT-19
  - name: XCT-20
  - path: /Users/kanha/BAM_kgupta/radiographic_identifier/config/config.yaml